org: ajaythiyo
app: my-node-api
service: my-node-api
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

functions:
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get

  greet:
    handler: greet.greet
    events:
      - httpApi:
          path: /greet
          method: get

